version: "3"
services:
  prod-env-pub:
    build: prod-env-pub/.
    image: ros-galactic:prod-env-pub
    volumes:
      - ./../launch_files:/root/launch_files:ro
    command: /bin/bash -c "source /root/cpp_pub/share/cpp_pub/local_setup.bash && ros2 launch /root/launch_files/pub_launch.yml"
  prod-env-sub:
    build: prod-env-sub/.
    image: ros-galactic:prod-env-sub
    volumes:
      - ./../launch_files:/root/launch_files:ro
    command: /bin/bash -c "source /root/cpp_sub/share/cpp_sub/local_setup.bash && ros2 launch /root/launch_files/sub_launch.yml"